theme = "sunset"
[editor.file-picker]
hidden = false
[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
